foil_info = {
    "game_foil": {'all_concepts':[["Butterfly box activated",
                                   "The butterfly box (on the bottom right of the image) is activated. The butterfly box when activated has a pink color.",
                                   "/static/foils/game_foil/concepts/concept_switch_on/image.png"],
["Empty left", "The cell to the left of Sokoban (the little green character) is empty.",
             "/static/foils/game_foil/concepts/concept_empty_left/image.png"],
 ["Box is below", "The box is in the cell below Sokoban (the little green character)",
             "/static/foils/game_foil/concepts/concept_box_below/image.png"],
 ["Target is on right", "The red target is in the cell right to Sokoban (the little green character)",
             "/static/foils/game_foil/concepts/concept_target_right/image.png"],
 ["Butterfly box on right",
             "The butterfly box is in the cell right of Sokoban (the little green character). The butterfly box has been marked on the image.",
             "/static/foils/game_foil/concepts/concept_left_switch/image.png"],
],
                  'test_images': [('test_image_1','/static/run_sokoban_game/test_images/image1.png', ['Butterfly box activated', 'Empty left']),
                                  ('test_image_2','/static/run_sokoban_game/test_images/image2.png', ['Butterfly box activated', 'Empty left']),
                                  ('test_image_3', '/static/run_sokoban_game/test_images/image3.png',
                                   ['Butterfly box activated', 'Empty left', 'Box is below']),
                                  ('test_image_4', '/static/run_sokoban_game/test_images/image4.png',
                                   ['Butterfly box activated', 'Target is on right']),
                                ('test_image_5', '/static/run_sokoban_game/test_images/image5.png',
                                   ['Butterfly box on right', 'Empty left'])
                                  ]

                  },
    "foil1": {
        "concepts": [
                        ["Skull on right", "This means there is skull right next to Joe on the right side", "/static/foils/foil1/concepts/skull_on_right.png"],
                        ["On highest platform", "This means Joe is on the highest platform ", "/static/foils/foil1/concepts/on_highest_platform.png"],
                        ["On middle platform", "This means Joe is on the middle platform", "/static/foils/foil1/concepts/on_middle_platform.png"],
                        ["On ground", "This means Joe is on the ground", "/static/foils/foil1/concepts/on_ground.png"],
                        ["On rope", "This means Joe is holding on to the rope", "/static/foils/foil1/concepts/on_rope.png"],
                        ["On first ladder", "This means Joe is on the leftmost ladder", "/static/foils/foil1/concepts/on_first_ladder.png"],
                        ["On second ladder", "This means Joe is on the middle ladder", "/static/foils/foil1/concepts/on_second_ladder.png"],
                        ["On third ladder", "This means Joe is on the rightmost ladder", "/static/foils/foil1/concepts/on_third_ladder.png"],
                        ["On left ledge", "This means Joe is on a ledge and there is no platform on the left side", "/static/foils/foil1/concepts/on_left_ledge.png"]
        ],
        "important_concept": ["Skull on left", "This means there is skull right next to Joe on the left side", "/static/foils/foil1/concepts/skull_on_left.png"],
        "plan_video_loc": "/static/foils/foil1/plan.mp4",
        "plan_goal": "Get to the key",
        "foil_image_loc": "/static/foils/foil1/foil.png",
        "foil_text": "Follow the plan till you are next to the skull as in the shown image, then move-left (instead of "
                     "jump-left) and then "
                     "follow the rest of the "
                     "plan. ",
        "foil_explanation": [
            ["simple_exp", "In the alternate plan, you can not perform the action move-left in the state shown in the image", "/static/foils/foil1/foil.png"],
            ["concept_exp", "You can not perform the action move-left in a state where -- \"Skull on left\" is True. Hence, the action move-left will fail in the alternate plan in the state shown in the image.", "/static/foils/foil1/foil.png"]
        ],
        "concept_rating_ques": {
            "concept_exp": "How complete was the explanation \"move left can’t be done when `skull on left` is True\"?",
            "simple_exp": "How complete was the explanation \"move left can’t be done?\""
        }
    },
    "foil2": {
        "concepts": [
                        ["Skull on left", "This means there is skull right next to Joe on the left side", "/static/foils/foil1/concepts/skull_on_left.png"],
                        ["Skull on right", "This means there is skull right next to Joe on the right side", "/static/foils/foil1/concepts/skull_on_right.png"],
                        ["On highest platform", "This means Joe is on the highest platform ", "/static/foils/foil1/concepts/on_highest_platform.png"],
                        ["On middle platform", "This means Joe is on the middle platform", "/static/foils/foil1/concepts/on_middle_platform.png"],
                        ["On ground", "This means Joe is on the ground", "/static/foils/foil1/concepts/on_ground.png"],
                        ["On first ladder", "This means Joe is on the leftmost ladder", "/static/foils/foil1/concepts/on_first_ladder.png"],
                        ["On second ladder", "This means Joe is on the middle ladder", "/static/foils/foil1/concepts/on_second_ladder.png"],
                        ["On third ladder", "This means Joe is on the rightmost ladder", "/static/foils/foil1/concepts/on_third_ladder.png"],
                        ["On left ledge", "This means Joe is on a ledge and there is no platform on the left side", "/static/foils/foil1/concepts/on_left_ledge.png"]
        ],
        "important_concept": ["On rope", "This means Joe is holding on to the rope", "/static/foils/foil1/concepts/on_rope.png"],
        "plan_video_loc": "/static/foils/foil1/plan.mp4",
        "plan_goal": "Get to the key",
        "foil_image_loc": "/static/foils/foil2/foil.png",
        "foil_text": "Follow the plan till you are on the ropes, instead of jump-right, just perform move-right, "
                     "and once "
                     "on platform follow the rest of the plan.",
        "foil_explanation": [
            ["simple_exp", "In the alternate plan, you can not perform the action move-right in the state shown in the image", "/static/foils/foil2/foil.png"],
            ["concept_exp", "You can not perform the action move-right in a state where -- \"on the rope\" is True. Hence, the action move-right will fail in the alternate plan in the state shown in the image.", "/static/foils/foil2/foil.png"]
        ],
        "concept_rating_ques": {
            "concept_exp": "How complete was the explanation \"move-right can’t be done when `on the rope` is True\"?",
            "simple_exp": "How complete was the explanation \"move-right can’t be done?\""
        }
    },
    "foil3": {
        "concepts": [
                        ["Skull on left", "This means there is skull right next to Joe on the left side", "/static/foils/foil1/concepts/skull_on_left.png"],
                        ["Skull on right", "This means there is skull right next to Joe on the right side", "/static/foils/foil1/concepts/skull_on_right.png"],
                        ["On highest platform", "This means Joe is on the highest platform ", "/static/foils/foil1/concepts/on_highest_platform.png"],
                        ["On middle platform", "This means Joe is on the middle platform", "/static/foils/foil1/concepts/on_middle_platform.png"],
                        ["On ground", "This means Joe is on the ground", "/static/foils/foil1/concepts/on_ground.png"],
                        ["On rope", "This means Joe is holding on to the rope", "/static/foils/foil1/concepts/on_rope.png"],
                        ["On first ladder", "This means Joe is on the leftmost ladder", "/static/foils/foil1/concepts/on_first_ladder.png"],
                        ["On second ladder", "This means Joe is on the middle ladder", "/static/foils/foil1/concepts/on_second_ladder.png"],
                        ["On third ladder", "This means Joe is on the rightmost ladder", "/static/foils/foil1/concepts/on_third_ladder.png"]
        ],
        "important_concept": ["On left ledge", "This means Joe is on a ledge and there is no platform on the left side", "/static/foils/foil1/concepts/on_left_ledge.png"],
        "plan_video_loc": "/static/foils/foil1/plan.mp4",
        "plan_goal": "Get to the key",
        "foil_image_loc": "/static/foils/foil3/foil.png",
        "foil_text": "Follow the plan till you are on middle platform, instead of using the ladder, move to the edge "
                     "then move-left and then follow the same plan",
        "foil_explanation": [
            ["simple_exp", "In the alternate plan, you can not perform the action move-left in the state shown in the image", "/static/foils/foil3/foil.png"],
            ["concept_exp", "You can not perform the action move-left in a state where -- \"on left edge\" is True. Hence, the action move-left will fail in the alternate plan in the state shown in the image.", "/static/foils/foil3/foil.png"]
        ],
        "concept_rating_ques": {
            "concept_exp": "How complete was the explanation \"move-left can’t be done when `on left edge` is True\"?",
            "simple_exp": "How complete was the explanation \"move-left can’t be done?\""
        }
    },
    "foil4": {
        "concepts": [
                        ["On ladder", "Joe is on a ladder.", "/static/foils/foil4/concepts/on_ladder.png"],
                        ["In Air", "Joe is in the air.", "/static/foils/foil4/concepts/in_air.png"],
                        ["Ladder is clear above", "Joe is on the ladder and there is no spider above Joe.", "/static/foils/foil4/concepts/is_clear_above.png"],
                        ["Spider on Relative Left", "Spider lies to left of Joe", "/static/foils/foil4/concepts/spider_on_relative_left.png"],
                        ["Spider on Relative Right", "Spider lies to the right of Joe", "/static/foils/foil4/concepts/spider_on_relative_right.png"],
                        ["Spider on left", "Joe is right next to the spider and the spider is on the left", "/static/foils/foil4/concepts/spider_on_left.png"],
                        ["Spider on right", "Joe is right next to the spider and the spider is on the right", "/static/foils/foil4/concepts/spider_on_right.png"],
                        ["On Bottom Ladder", "Joe is on the bottom ladder (below the platform)", "/static/foils/foil4/concepts/on_bottom_ladder.png"],
                        ["On Top Ladder", "Joe is on the top ladder (above the platform)", "/static/foils/foil4/concepts/on_top_ladder.png"],
                        ["On Left Passage", "Joe is in the left passage", "/static/foils/foil4/concepts/on_left_passage.png"],
                        ["On Right Passage", "Joe is on the right passage", "/static/foils/foil4/concepts/on_right_passage.png"],
        ],
        "important_concept": ["Ladder is clear below", "Joe is on the ladder and there is no spider below Joe. ", "/static/foils/foil4/concepts/is_clear_below.png"],
        "plan_video_loc": "/static/foils/foil4/plan.mp4",
        "plan_goal": "Get to the ladder's end at the bottom",
        "foil_image_loc": "/static/foils/foil4/foil.png",
        "foil_text": "At the beginning of the plan, instead of waiting, move down the ladder",
        "foil_explanation": [
            ["simple_exp", "In the alternate plan, you can not perform the action move-down in the state shown in the image", "/static/foils/foil4/foil.png"],
            ["concept_exp", "You can only perform the action move-down in a state where -- \"Ladder is clear below\" is True. Hence, the action move-down will fail in the alternate plan in the state shown in the image.", "/static/foils/foil4/foil.png"]
        ],
        "concept_rating_ques": {
            "concept_exp": "How complete was the explanation \"move-down can only be performed when `Ladder is clear below` is True\"?",
            "simple_exp": "How complete was the explanation \"move-down cannot be done?\""
        }
    },
    "foil5": {
        "concepts": [
            ["Above butterfly box",
             "Sokoban is in the cell right above the butterfly box. The butterfly box has been marked on the image.",
             "/static/foils/foil5/concepts/concept_above_switch/image.png"],
            ["Box is below", "The box is in the cell below Sokoban",
             "/static/foils/foil5/concepts/concept_box_below/image.png"],
            ["Empty above", "The cell above Sokoban is empty.",
             "/static/foils/foil5/concepts/concept_empty_above/image.png"],
            ["Empty below", "The cell below Sokoban is empty.",
             "/static/foils/foil5/concepts/concept_empty_below/image.png"],
            ["Empty left", "The cell to the left of Sokoban is empty.",
             "/static/foils/foil5/concepts/concept_empty_left/image.png"],
            ["Empty right", "The cell to the right of Sokoban is empty",
             "/static/foils/foil5/concepts/concept_empty_right/image.png"],
            ["Butterfly box on right",
             "The butterfly box is in the cell right of Sokoban. The butterfly box has been marked on the image.",
             "/static/foils/foil5/concepts/concept_left_switch/image.png"],
            ["Target is above ", "The red target is in the cell above Sokoban",
             "/static/foils/foil5/concepts/concept_target_above/image.png"],
            ["Target is below", "The red target is in the cell below Sokoban",
             "/static/foils/foil5/concepts/concept_target_below/image.png"],
            ["Target is on left", "The red target is in the cell left to Sokoban",
             "/static/foils/foil5/concepts/concept_target_left/image.png"],
            ["Target is on right", "The red target is in the cell right to Sokoban",
             "/static/foils/foil5/concepts/concept_target_right/image.png"],
            ["Wall above", "There is a wall in the cell above Sokoban",
             "/static/foils/foil5/concepts/concept_wall_above/image.png"],
            ["Wall below", "There is a wall in the cell below Sokoban",
             "/static/foils/foil5/concepts/concept_wall_below/image.png"],
            ["Wall on left", "There is a wall in the cell left of Sokoban",
             "/static/foils/foil5/concepts/concept_wall_left/image.png"],
            ["Wall below and on left", "There is a wall in the cell left of and the cell below the box",
             "/static/foils/foil5/concepts/concept_wall_left_below_ofbox/image.png"],
            ["Wall on right", "There is a wall in the cell right of Sokoban",
             "/static/foils/foil5/concepts/concept_wall_right/image.png"]
        ],
        "important_concept": ["Butterfly box activated",
                              "The butterfly box (marked on the image) is activated. The butterfly box when activated has a pink color.",
                              "/static/foils/foil5/concepts/concept_switch_on/image.png"],
        "plan_video_loc": "/static/foils/foil5/plan.mp4",
        "plan_goal": "Push the box into the red target",
        "foil_image_loc": "/static/foils/foil5/foil.png",
        "foil_text": "At the beginning of the plan, instead of going right, directly push the box towards its target",
        "foil_explanation": [
            ["simple_exp", [
                "Step-1: 'push up' action costs 10.",
                "Step-2: 'push up' action costs 10.",
                "Step-3: 'push up' action costs 10.",
                "Step-4: 'push up' action costs 10.",
                "Total-cost of the alternate plan is 40. Proposed plan only costs 10."],
                [
                    "/static/foils/foil5/foil_images/step1.png",
                    "/static/foils/foil5/foil_images/step2.png",
                    "/static/foils/foil5/foil_images/step3.png",
                    "/static/foils/foil5/foil_images/step4.png",
                ]
             ],
            ["concept_exp", [
                "Executing action \"push up\" when \"Butterfly box activated\" is false costs at least 10.",
                "This is happening in the steps 1, 2, 3 and 4",
                "Thus, total-cost of the alternate plan is at least 40. Proposed plan only costs 10."],
                [
                     "/static/foils/foil5/foil_images/step1.png",
                     "/static/foils/foil5/foil_images/step2.png",
                     "/static/foils/foil5/foil_images/step3.png",
                     "/static/foils/foil5/foil_images/step4.png",
                 ]
             ],
        ],
        "concept_rating_ques": {
            "concept_exp": "How complete was the explanation \"move-down can only be performed when `Ladder is clear below` is True\"?",
            "simple_exp": "How complete was the explanation \"move-down cannot be done?\""
        }
    },
    "foil6": {
            "concepts": [['Blank cell below',
              'There is a blank cell below Sokoban',
              '/static/foils/foil6/concepts/concept_blank_cell_below/image.png'],
             ['Blank cell on left',
              'There is a blank cell on the left of Sokoban',
              '/static/foils/foil6/concepts/concept_blank_cell_on_left/image.png'],
             ['No pink cells below for at least 2 cells',
              'At least the two cells below the sokoban are not pink cells',
              '/static/foils/foil6/concepts/concept_no_pink_cell_below_m/image.png'],
             ['No pink cell on top for at least 2 cells',
              'At least two cells above the Sokoban are not pink cells',
              '/static/foils/foil6/concepts/concept_no_pink_cell_on_top_m/image.png'],
             ['No wall below for at least 2 cells',
              'At least two cells below the Sokoban do not contain wall',
              '/static/foils/foil6/concepts/concept_no_wall_below_m/image.png'],
             ['No wall on left for at least 2 cells',
              'At least two cells on the left of Sokoban do not contain wall',
              '/static/foils/foil6/concepts/concept_no_wall_on_left_m/image.png'],
             ['No wall on right for at least 2 cells',
              'At least two cells on the right of Sokoban do not contain wall',
              '/static/foils/foil6/concepts/concept_no_wall_on_right_m/image.png'],
             ['No wall above for at least 2 cells',
              'At least two cells above the Sokoban do not contain wall',
              '/static/foils/foil6/concepts/concept_no_wall_on_top_m/image.png'],
             ['Pink cell below',
              'There is a pink cell below the Sokoban',
              '/static/foils/foil6/concepts/concept_pink_cell_below/image.png'],
             ['Pink cell on left',
              'There is a pink cell on the left of Sokoban',
              '/static/foils/foil6/concepts/concept_pink_cell_on_left/image.png'],
             ['Pink cell on right',
              'There is a pink cell on the right of Sokoban',
              '/static/foils/foil6/concepts/concept_pink_cell_on_right/image.png'],
             ['Pink cell on top',
              'There is a pink cell on top of Sokoban',
              '/static/foils/foil6/concepts/concept_pink_cell_on_top/image.png'],
             ['Target on right',
              'The target cell is on the right of Sokoban',
              '/static/foils/foil6/concepts/concept_target_on_right/image.png'],
             ['Target on top',
              'The target cell is on the top of Sokoban',
              '/static/foils/foil6/concepts/concept_target_on_top/image.png'],
             ['Wall above box',
              'There is a wall above the box',
              '/static/foils/foil6/concepts/concept_wall_above_box/image.png'],
             ['Wall below box',
              'There is a wall below the box',
              '/static/foils/foil6/concepts/concept_wall_below/image.png'],
             ['Wall below Sokoban',
              'There is wall below Sokoban',
              '/static/foils/foil6/concepts/concept_wall_below/image.png'],
             ['Wall below and on left of Sokoban',
              'There is a wall below and on the left of Sokoban',
              '/static/foils/foil6/concepts/concept_wall_down_left/image.png'],
             ['Wall below and on right of Sokoban',
              'There is a wall below and on the right of Sokoban',
              '/static/foils/foil6/concepts/concept_wall_down_right/image.png'],
             ['Wall on left of Sokoban',
              'There is a wall on the left of Sokoban',
              '/static/foils/foil6/concepts/concept_wall_on_left/image.png'],
             ['Wall on left of box',
              'There is a wall on the left of the box',
              '/static/foils/foil6/concepts/concept_wall_on_left_of_box/image.png'],
             ['Wall on right of Sokoban',
              'There is a wall on the right of Sokoban',
              '/static/foils/foil6/concepts/concept_wall_on_right/image.png'],
             ['Wall on right of box',
              'There is a wall to the right of box',
              '/static/foils/foil6/concepts/concept_wall_on_right_of_box/image.png'],
             ['Wall on top',
              'There is a wall on top of Sokoban',
              '/static/foils/foil6/concepts/concept_wall_on_top/image.png'],
             ['Wall on left and top of Sokoban',
              'There is a wall on the left and on top of Sokoban',
              '/static/foils/foil6/concepts/concept_wall_top_left/image.png'],
             ['Wall on right and top of Sokoban',
              'There is a wall on the right and on top of Sokoban',
              '/static/foils/foil6/concepts/concept_wall_top_right/image.png'],
             ['Wall on right, above and below Sokoban',
              'There is a wall on the right of, above and below Sokoban',
              '/static/foils/foil6/concepts/concept_wall_up_down_right/image.png']],
            "important_concept": ['Box on pink cell',
                      'The box is present on the pink cell',
                      '/static/foils/foil6/concepts/concept_on_pink_cell/image.png'],
            "plan_video_loc": "/static/foils/foil6/plan.mp4",
            "plan_goal": "Push the box into the red target",
            "foil_image_loc": "/static/foils/foil6/foil.png",
            "foil_text": "Instead of pushing the box around the pink cells, directly push the box through them and then proceed to push it to the target.",
            "foil_explanation": [
                ["simple_exp", [
                    "Step-1: 'push up' action costs 1.",
                    "Step-2: 'push up' action costs 1.",
                    "Step-3: 'push up' action costs 10.",
                    "Step-4: 'push up' action costs 10.",
                    "Step-5: 'push up' action costs 10.",
                    "Step-6: 'push up' action costs 1.",
                    "Step-7: 'move left' action costs 1.",
                    "Step-8: 'move up' action costs 1.",
                    "Step-9: 'push right' action costs 1.",
                    "Total-cost of the alternate plan is 36. Proposed plan only costs 11."],
                    [
                        "/static/foils/foil6/foil_images/step2.png",
                        "/static/foils/foil6/foil_images/step3.png",
                        "/static/foils/foil6/foil_images/step4.png",
                        "/static/foils/foil6/foil_images/step5.png",
                        "/static/foils/foil6/foil_images/step6.png",
                        "/static/foils/foil6/foil_images/step7.png",
                        "/static/foils/foil6/foil_images/step8.png",
                        "/static/foils/foil6/foil_images/step9.png",
                        "/static/foils/foil6/foil_images/step10.png"
                    ]
                 ],
                ["concept_exp", [
                    "Executing action 'push up' action costs at least 1",
                    "This is happening in the steps 1, 2 and 6",
                    "------------------------------------------------",
                    "Executing action \"push up\" when \"Box on pink cell\" is true costs at least 10.",
                    "This is happening in the steps 3, 4 and 5",
                    "------------------------------------------------",
                    "'move left' action costs at least 1. This happens in step 7",
                    "------------------------------------------------",
                    "'move up' action costs at least 1. This happens in step 8",
                    "------------------------------------------------",
                    "'push right' action costs at least 1. This happens in step 9",
                    "------------------------------------------------",
                    "Thus, total-cost of the alternate plan is at least 36. Proposed plan only costs 11."],
                    [
                        "/static/foils/foil6/foil_images/step2.png",
                        "/static/foils/foil6/foil_images/step3.png",
                        "/static/foils/foil6/foil_images/step4.png",
                        "/static/foils/foil6/foil_images/step5.png",
                        "/static/foils/foil6/foil_images/step6.png",
                        "/static/foils/foil6/foil_images/step7.png",
                        "/static/foils/foil6/foil_images/step8.png",
                        "/static/foils/foil6/foil_images/step9.png",
                        "/static/foils/foil6/foil_images/step10.png"
                    ]
                 ],
            ],
            "concept_rating_ques": {
                "concept_exp": "How complete was the explanation \"move-down can only be performed when `Ladder is clear below` is True\"?",
                "simple_exp": "How complete was the explanation \"move-down cannot be done?\""
            }
        }
  }
